# By https://blog.70-10.net/2020/05/31/github-actions-deploy-netlify/

name: Deploy_Netlify

on:
  push:
    branches: [ master ]
#    pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test 
      - name: Publish
        uses: netlify/actions/cli@master
        env:
           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
         args: deploy --dir=public --prod
         secrets: '["NETLIFY_SITE_ID", "NETLIFY_AUTH_TOKEN"]'
